### ISSUE TITLE
META - Create documentation

### ISSUE THREAD

**Issue by pavithraes** [Quansight/ragna#24]
```[tasklist]
### Setup
- [x] Setup docs infrastructure - ref: #38
- [x] Setup docs framework
- [ ] https://github.com/Quansight/ragna/issues/148
- [ ] https://github.com/Quansight/ragna/issues/44
- [ ] https://github.com/Quansight/ragna/issues/68
- [x] Add Plausible for recording visitors info - #143
```
```[tasklist]
### Content - Narrative
- [ ] https://github.com/Quansight/ragna/issues/36
- [x] Tutorial: Python API
- [ ] Tutorial: REST
- [ ] Tutorial: Web App
- [ ] What is RAG?
- [ ] Brand
- [x] Welcome
- [x] Installation
```

```[tasklist]
### References
- [ ] https://github.com/Quansight/ragna/pull/60
- [ ] https://github.com/Quansight/ragna/pull/63
- [ ] https://github.com/Quansight/ragna/issues/69
- [x] FAQ
- [ ] https://github.com/Quansight/ragna/issues/90
- [ ] https://github.com/Quansight/ragna/issues/109
```

```[tasklist]
### Misc
- [ ] Make it clear that vector db == source storage and llm == assistant in Ragna
- [ ] Move "What is Rag" to the top
- [ ] https://github.com/Quansight/ragna/pull/100#discussion_r1371899595
```

**Comment by pmeier** [comment]
@pavithraes can we close this now that the `0.1.0` release is out or do we need to update the milestone?

**Comment by pmeier** [comment]
We have documentation now. We can open another tracker issue in case we want to have a larger refactor. Otherwise, we can probably work with a few smaller issues.
