### ISSUE TITLE
META - Project health files

### ISSUE THREAD

**Issue by pavithraes** [Quansight/ragna#25]
```[tasklist]
### Tasks
- [x] Labels and milestones
- [x] Issue & PR Templates
- [x] README enhancement (CoC note)
- [x] LICENSE
- [x] Branch protections
- [x] security policy
- [x] precommit hooks (#38)
```

Removed roadmap and release strategy as non-critical, will open a separate issue with nice to have's

**Comment by pavithraes** [comment]
Closing as complete 🚀
