### ISSUE TITLE
META - Marketing

### ISSUE THREAD

**Issue by pavithraes** [Quansight/ragna#27]
```[tasklist]
### Tasks
- [ ] https://github.com/Quansight/ragna/issues/45
- [ ] https://github.com/Quansight/ragna/issues/80
- [ ] https://github.com/Quansight/ragna/issues/79
- [x] Social media announcement posts
- [x] CFP for PyData NYC
- [x] CFP for PyData Global
- [x] Promote in NF newsletter (Kate)
```

**Comment by pavithraes** [comment]
✅
